#!/bin/env sh

# This file is part of the Roverbar MP3-Station.
#
# The Roverbar MP3-Station is free software: you can redistribute it 
# and/or modify it under the terms of the GNU General Public License 
# as published by the Free Software Foundation, either version 3 of 
# the License, or (at your option) any later version.
# 
# The Roverbar MP3-Station is distributed in the hope that it 
# will be useful, but WITHOUT ANY WARRANTY; without even the 
# implied warranty of MERCHANTABILITY or FITNESS FOR A 
# PARTICULAR PURPOSE.  See the GNU General Public License for 
# more details.
#
# You should have received a copy of the GNU General Public License
# along with the Roverbar MP3-Station.  If not, see 
# <http://www.gnu.org/licenses/>.
#
# 2007 - Lucas S. Bickel v/o Karbon <karbon@pfadipatria.com>
#
# This gets used to create a new exports file on each boot
# see /etc/netgroups for the allowed ip ranges
# someday this might get spruced up to also configure avahi

EXPORTFS_FILE=/etc/exports

echo "# This file is generated by /root/bin/make_exportfs.sh do not edit by hand" >$EXPORTFS_FILE
echo >> $EXPORTFS_FILE

awk '/^\/dev.*\/media/ {print $2}' /etc/fstab | sed 's/\(.*\)/\1\t192.168.0.*(rw,no_subtree_check)/ 10.*.*.*(rw,no_subtree_check)' - >> $EXPORTFS_FILE

exportfs -r 
